# nnictl create --config ./auto_hyper/model_config.yaml --port 8060
experimentName: Your_Experiment_Name
max_trial_number: 100

searchSpaceFile: model_search_space.json

trialCommand: python train_with_split.py dataset="Sports" output_dir="/home/zsj/pretrained-models/Sports" model.batch_size=1024 model.learning_rate=2e-3 model.num_epochs=100 model.data_interaction_files="./data/Sports/user2item.pkl" model.data_text_files="./data/Sports/item2title.pkl"

trialCodeDirectory: ..

trialGpuNumber: 1       # 每块 GPU 上多少个实验
trial_concurrency: 4    # 多少个实验一起跑


tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize

trainingService:
  platform: local
  maxTrialNumberPerGpu: 1
  useActiveGpu: true
  gpuIndices: [0,1,2,3]