# nnictl create --config ./auto_hyper/post_train_config.yaml --port 8060
experimentName: Your_Experiment_Name
max_trial_number: 300

searchSpaceFile: post_train_search_space.json

trialCommand: python train_with_rl.py dataset="Beauty" output_dir="/home/zsj/pretrained-models/Beauty"  post_training.pretrained_model_path="/home/zsj/pretrained-models/Beauty/generation_model"  tokenizer.data_text_files="./data/Beauty/item2title.pkl"  tokenizer.interaction_files="./data/Beauty/user2item.pkl"  model.data_interaction_files="./data/Beauty/user2item.pkl"   model.data_text_files="./data/Beauty/item2title.pkl"  skip_model=True 

trialCodeDirectory: ..

trialGpuNumber: 1       # 每块 GPU 上多少个实验
trial_concurrency: 4    # 多少个实验一起跑


tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize

trainingService:
  platform: local
  maxTrialNumberPerGpu: 1
  useActiveGpu: true
  gpuIndices: [0,1,2,3]