# config/online_rl/rankpo.yaml

trainer:
  _target_: genrec.trainers.online_rl.rankpo_trainer.RankPOTrainer
  _partial_: true
  beta: 1
  tau1: 3
  tau2: 3
  num_generations: 4
  # RankPO doesn't need reward_func

pretrained_model: "/home/zsj/pretrained-models/Beauty-Official/generation_model"
save_model_path: "/home/zsj/pretrained-models/Beauty-PostTrain-RankPO"