# config/generative.yaml

defaults:
  - _self_
  - model: t5
  - tokenizer: rqvae
  - generative: tiger 

dataset: "Beauty"
output_dir: "./Beauty"
cuda: "0"
force_retrain_tokenizer: false
force_retrain_model: false
skip_tokenizer: false
skip_model: false
seed: 42