# config/offline_rl.yaml

defaults:
  - _self_
  - model: t5
  - tokenizer: rqvae
  - offline_rl: sdpo  # ðŸ”¥ æŒ‡å®šä½¿ç”¨çš„ trainer

dataset: "Beauty"
output_dir: "/home/zhenxiangxv/GR-Benchmark/pushVersion/Generative-Recommendation-Benchmark/Beauty"
cuda: "0"
force_retrain_tokenizer: false
force_retrain_model: false
skip_tokenizer: false
skip_model: false
seed: 42